services:
  dev:
    image: node:22-alpine
    user: ${uid:-1000}:${gid:-1000}
    environment:
      NODE_ENV: development
      npm_config_cache: /src/.npm
    volumes:
      - ./:/src
    ports:
      - 9229:9229
    working_dir: /src
    command: npm run debug-test